---
- hosts: vagrant
  sudo: yes
  vars:
  roles:
    - role: ./common-roles/base
    - role: ./common-roles/ruby
    # - role: ./common-roles/nginx
    - role: ./common-roles/nginx-passenger
  tasks:
    - yum: name=redis state=installed
      name: be sure redis installed
    - service: name=redis state=running enabled=yes
      name: be sure redis runninng and enabled
