---
- hosts: vagrant
  sudo: yes
  vars:
  roles:
    - role: ./common-roles/base
    - role: ./common-roles/ruby
    # - role: ./common-roles/nginx
    - role: ./common-roles/nginx-passenger
  tasks:

