---
- hosts: vagrant
  sudo: yes
  vars:
  roles:
    - role: ./common-roles/base
    - role: ./common-roles/ruby
    # - role: ./common-roles/nginx
    - role: ./common-roles/nginx-passenger
    - role: ./common-roles/redis
    - role: ./common-roles/mysql_devel
  tasks:
    - yum: name=mlocate state=installed
      name: install locate command
    - yum: name=telnet state=installed
      name: install telnet command
    - yum: name=bind-utils state=installed
      name: install nslookup command
    - yum: name=vim-enhanced state=installed
      name: install vim
    - yum: name=zsh state=installed
      name: install zsh
    - yum: name=tmux state=installed
      name:  install tmux
