---
  - yum: name=* state=latest
    name: be sure updated to latest packages

  - yum: name=yum-plugin-fastestmirror state=installed
    name: be sure yum-plugin-fastestmirror installed

  - yum: name="@Development tools" state=installed
    name: be sure Development tools installed

  - yum: name=mlocate state=installed
    name: install locate command
  - yum: name=telnet state=installed
    name: install telnet command
  - yum: name=bind-utils state=installed
    name: install nslookup command
  - yum: name=vim-enhanced state=installed
    name: install vim
  - yum: name=zsh state=installed
    name: install zsh
  - yum: name=tmux state=installed
    name:  install tmux
